name: flutter_memory_game
description: Flutter Memory Game

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  #State Management
  provider: ^6.0.4

  #icons
  fluttericon: ^2.0.0

  #Local Storage
  flutter_secure_storage: ^9.2.4

  #Lottie animations
  lottie: ^2.0.0
  audioplayers: ^6.5.1
  just_audio: ^0.10.5
  google_fonts: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/game_bg_jpeg/
      - assets/game_card_png/
      - assets/splash_jpeg/
      - assets/animations_json/
      - assets/home_bg_jpeg/
      - assets/icons_png/
      - assets/sounds/events/1000-iq.mp3
      - assets/sounds/events/angels.mp3
      - assets/sounds/events/anime-wow-sound-effect-mp3cut.mp3
      - assets/sounds/events/apple-pay-sound.mp3
      - assets/sounds/events/ara-ara.mp3
      - assets/sounds/events/baka.mp3
      - assets/sounds/events/brother-ewwwwwww.mp3
      - assets/sounds/events/bruh.mp3
      - assets/sounds/events/bye.mp3
      - assets/sounds/events/ceeday-huh-sound-effect.mp3
      - assets/sounds/events/censor-beep-7.mp3
      - assets/sounds/events/cgirl_laugh.mp3
      - assets/sounds/events/chainsaw-sound-effects.mp3
      - assets/sounds/events/chara-creepy-sound.mp3
      - assets/sounds/events/chomp-1.mp3
      - assets/sounds/events/click.mp3
      - assets/sounds/events/collecting-gems.mp3
      - assets/sounds/events/confetti-pop-sound.mp3
      - assets/sounds/events/cook_dog.mp3
      - assets/sounds/events/correct.mp3
      - assets/sounds/events/cs_okay.mp3
      - assets/sounds/events/cute-cat-meowming.mp3
      - assets/sounds/events/desert-eagle-cs.mp3
      - assets/sounds/events/ding.mp3
      - assets/sounds/events/drinking-slurping.mp3
      - assets/sounds/events/electric-shock.mp3
      - assets/sounds/events/error-glitch.mp3
      - assets/sounds/events/fbi.mp3
      - assets/sounds/events/female-ghost-laugh.mp3
      - assets/sounds/events/flashbang-sound-effect.mp3
      - assets/sounds/events/formula-1-box-box.mp3
      - assets/sounds/events/giggle.mp3
      - assets/sounds/events/goodnight-hd.mp3
      - assets/sounds/events/gsm-brushing-teeth.mp3
      - assets/sounds/events/gun_load.mp3
      - assets/sounds/events/happy-happy-happy-cat.mp3
      - assets/sounds/events/hi-there.mp3
      - assets/sounds/events/hohoho.mp3
      - assets/sounds/events/huh-cat.mp3
      - assets/sounds/events/ice.mp3
      - assets/sounds/events/joker-laughing.mp3
      - assets/sounds/events/kid_yay.mp3
      - assets/sounds/events/knocking.mp3
      - assets/sounds/events/let-him-cook-now.mp3
      - assets/sounds/events/let_cook.mp3
      - assets/sounds/events/magic-fairy.mp3
      - assets/sounds/events/mario-meow.mp3
      - assets/sounds/events/meow-1.mp3
      - assets/sounds/events/meow.mp3
      - assets/sounds/events/metal_alert.mp3
      - assets/sounds/events/minecraft-glass-break.mp3
      - assets/sounds/events/money.mp3
      - assets/sounds/events/nani.mp3
      - assets/sounds/events/night-vision-on.mp3
      - assets/sounds/events/no-no-wait-wait.mp3
      - assets/sounds/events/nope.mp3
      - assets/sounds/events/notepad.mp3
      - assets/sounds/events/no_time.mp3
      - assets/sounds/events/ns-ding-dong.mp3
      - assets/sounds/events/nuclear-alarm-siren.mp3
      - assets/sounds/events/oh_hel_no.mp3
      - assets/sounds/events/okay.mp3
      - assets/sounds/events/pentakill-lol.mp3
      - assets/sounds/events/pikachu_scream.mp3
      - assets/sounds/events/pizza.mp3
      - assets/sounds/events/planting-c4-csgo.mp3
      - assets/sounds/events/pop.mp3
      - assets/sounds/events/pou-sound-effect.mp3
      - assets/sounds/events/pouring.mp3
      - assets/sounds/events/press-f-to-pay-respects.mp3
      - assets/sounds/events/prison-cell-door-lock.mp3
      - assets/sounds/events/question-mark.mp3
      - assets/sounds/events/ragnarok-online-level-up-sound.mp3
      - assets/sounds/events/record-scratch-2.mp3
      - assets/sounds/events/rizz-sound-effect.mp3
      - assets/sounds/events/scratch-cat-meow.mp3
      - assets/sounds/events/shark-swimming-fast.mp3
      - assets/sounds/events/shock.mp3
      - assets/sounds/events/shotgun.mp3
      - assets/sounds/events/snap.mp3
      - assets/sounds/events/spanish_laugh.mp3
      - assets/sounds/events/squeak.mp3
      - assets/sounds/events/steve_hurt.mp3
      - assets/sounds/events/stupid.mp3
      - assets/sounds/events/super-mario-coin-sound.mp3
      - assets/sounds/events/tada.mp3
      - assets/sounds/events/tennis-shot.mp3
      - assets/sounds/events/tir-dak47.mp3
      - assets/sounds/events/tryhard-man.mp3
      - assets/sounds/events/typing-sound-efffect.mp3
      - assets/sounds/events/uwu.mp3
      - assets/sounds/events/villager.mp3
      - assets/sounds/events/waitscorp.mp3
      - assets/sounds/events/william-dafoe-laugh.mp3
      - assets/sounds/events/windows-10-error-sound.mp3
      - assets/sounds/events/wow.mp3
      - assets/sounds/events/wrong.mp3
      - assets/sounds/events/yamate.mp3
      - assets/sounds/events/yippie.mp3
      - assets/sounds/events/sword.mp3
      - assets/sounds/error.mp3
      - assets/sounds/correctx3.mp3



  