name: flutter_memory_game
description: Flutter Memory Game

version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

  #State Management
  provider: ^6.0.4

  #icons
  fluttericon: ^2.0.0

  #Local Storage
  flutter_secure_storage: ^9.2.4

  #Lottie animations
  lottie: ^2.0.0
  audioplayers: ^6.5.1
  just_audio: ^0.10.5
  google_fonts: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/game_bg_jpeg/
      - assets/game_card_png/
      - assets/splash_jpeg/
      - assets/animations_json/
      - assets/home_bg_jpeg/
      - assets/icons_png/
      - assets/sounds/backgrounds/d_gray.mp3
      - assets/sounds/events/angels.mp3
      - assets/sounds/events/bruh.mp3
      - assets/sounds/events/click.mp3
      - assets/sounds/events/ice.mp3
      - assets/sounds/events/nope.mp3
      - assets/sounds/events/pop.mp3
      - assets/sounds/events/snap.mp3
      - assets/sounds/events/wow.mp3

  